include(CheckCCompilerFlag)
include(CheckLinkerFlag)

function(phpshield_add_c_flag_if_supported target flag)
  string(MAKE_C_IDENTIFIER "C_FLAG_${flag}" key)
  check_c_compiler_flag("${flag}" ${key})
  if(${key})
    target_compile_options(${target} PRIVATE "${flag}")
  endif()
endfunction()

function(phpshield_add_link_flag_if_supported target flag)
  string(MAKE_C_IDENTIFIER "LD_FLAG_${flag}" key)
  check_linker_flag(C "${flag}" ${key})
  if(${key})
    target_link_options(${target} PRIVATE "${flag}")
  endif()
endfunction()

function(phpshield_apply_hardening target)
  if(MSVC)
    phpshield_add_c_flag_if_supported(${target} "/W4")
  else()
    phpshield_add_c_flag_if_supported(${target} "-Wall")
    phpshield_add_c_flag_if_supported(${target} "-Wextra")
    phpshield_add_c_flag_if_supported(${target} "-Wno-unused-parameter")
  endif()
  
  if(CMAKE_BUILD_TYPE STREQUAL "Release")
    if(MSVC)
      phpshield_add_c_flag_if_supported(${target} "/guard:cf")
      phpshield_add_c_flag_if_supported(${target} "/GS")
      phpshield_add_c_flag_if_supported(${target} "/Qspectre")
      phpshield_add_link_flag_if_supported(${target} "/guard:cf")
      phpshield_add_link_flag_if_supported(${target} "/DYNAMICBASE")
      phpshield_add_link_flag_if_supported(${target} "/NXCOMPAT")
      phpshield_add_link_flag_if_supported(${target} "/OPT:REF")
      phpshield_add_link_flag_if_supported(${target} "/OPT:ICF")
    else()
      phpshield_add_c_flag_if_supported(${target} "-fvisibility=hidden")
      phpshield_add_c_flag_if_supported(${target} "-fstack-protector-strong")
      phpshield_add_c_flag_if_supported(${target} "-O2")
      target_compile_definitions(${target} PRIVATE _FORTIFY_SOURCE=2)
      phpshield_add_link_flag_if_supported(${target} "-Wl,-z,relro")
      phpshield_add_link_flag_if_supported(${target} "-Wl,-z,now")
      find_program(STRIP_TOOL NAMES strip)
      if(STRIP_TOOL)
        add_custom_command(TARGET ${target} POST_BUILD COMMAND ${STRIP_TOOL} "$<TARGET_FILE:${target}>" || true)
      endif()
    endif()
  endif()
endfunction()
